### ISSUE TITLE
[FEATURE] Some requests

### ISSUE THREAD

**Issue by Drc-DEV** [VladimirWrites/AnalogWatchFace#11]
Hi, I'd like to propose some additions which would allow even more customizations with just a few more lines of code.
1) Add a scale slider for the Tick Marks Layout, so that one can adjust tick length without having to create a separate layout, or also in order to make the tick marks closer to the bezel of the watch for watches that have a dark ring on the frame (fossil gen5 for example).
2) Add an option to hide the minutes Tick Marks on ambient mode. In the current version of the app one could only hide the minutes tick marks for all the views, while it would be cooler if there was a switch to only hide them in ambient mode (like some of the stock fossil watchfaces do)
3) Add a wiki to the project with some kind of instructions on how to contribute graphically, for example I know some people who could add layouts to this project, and a brief introduction on how to add layouts would really help.
4) Since the background has a color left / color right option, I think it would be also cool to have such an option also for the hands and tick marks. This way a more realistic look could be achieved, for example 2 shades of gray for the tick marks could be setup to have a more "metallic" feel to the tick marks instead of a plain color.

Thanks for the great open source app, I'll try to contribute as soon as I have some free time on my hands.

**Comment by VladimirWrites** [comment]
Thank you very much for the comment, and thank you for using the watch face. :)

Let me try answering 1, 2, and 4 at once. :)
Currently, I have no problems adding these features when it comes to coding, but I am struggling with keeping the watch face easy to use and easy to understand. I am not UI/UX designer, and watch screens are small and don't fit a lot of data. So having all these settings on the screen is hard without killing usability.
How to describe that you are setting the left color of the gradient for minute ticks in a language that is understandable to everyone, and to also do it in ~5 words? :)
I don't want this watch face to be a niche product used only by developers. 
I also don't want to have a feature-heavy companion app, as that would increase the complexity of the project.
The only solution that I have in mind is to add a hidden/advanced menu in settings that would contain all these experimental and more complicated features.

And another point is that the main purpose of this project is to help people get into watch face development, so another problem is to keep the codebase understandable while adding more and more features. 
Even the initial project required 90 minutes course to describe it, and the current watch face is at least 10 times more complicated.

I will add a Dependency Injection solution using Hilt in the next couple of days, so that should reduce projects complexity a bit, and help with future changes.

For the next couple of months, my plan is:
- fix bugs (Samsung made a mess with their complications)
- improve the codebase to make it more accessible 
- write as many tests as I can so that I can start adding new features later on without breaking things

I will probably not add new features this year. There are also major library changes coming from Google that should be stable by the end of the year so I will need to migrate.

And regarding the 3rd point. I studied mathematics, so naturally :) almost everything drawn on the watch face is described by formulas in Polar coordinates. Also, there are some transformations that are converting round watch faces into a rectangular shape for Oppo watches which are pretty complicated. I don't know how to make this more accessible to someone who doesn't have at least some knowledge of trigonometry. 

Feel free to contribute, if you have time. Just push MR and I will check it. But if you plan to make bigger changes, ping me before so we can align and avoid conflicts. 

I hope that I managed to express myself clearly. If you have any ideas on how to overcome some of these problems, please share them :).

**Comment by Drc-DEV** [comment]
Thanks for the detailed answer, I really appreciate it.
Regarding the solution you have in mind (hidden menu), maybe just a toggle for "advanced options" would be better, which would then show all the "non-user-friendly" options in each menu. This would allow for more consistency in my opinion.
Regarding 3rd point, it would be easier (noob-friendly) to add more layouts if the app used scalable vector graphics for each design, which should still allow for transformations maybe. 

Anyways, great project and as-is is already the best analog watch face I have installed so far.
I contributed with Italian and French translations so far.

**Comment by VladimirWrites** [comment]
Thank you very much for the translations. They will be available in the next release. 
And thank you for your kind words. :) 
I don't have that much free time right now, so as I said I probably won't add new features this year, but I would like to have the advanced menu option next year. 
Regarding 3rd point, I was thinking about using vector graphics, but they have some limitations that I don't know how to handle.
For example, I don't know how to transform it for a rectangular watch face, or for a watch face with a chin.

In any case, I will convert this issue to discussion, and I will post updates there when I add new features.
