### ISSUE TITLE
Config layout error

### ISSUE THREAD

**Issue by Mirrodin1969** [VladimirWrites/AnalogWatchFace#2]
Hi...! Lovely of you to give this code. Thank you!

I'm very new, trying to learn. Can't understand most of it. Everything loads and runs fine on my Ticwatch Pro as a VD from AS 3.6...but when I enter config screen on watch (cog press) and scroll down, there is the option "Rate the Watch Face" then a big gap, thenI can just see part of the word "second" and I can see the word "hand" and the option slider circle thing is nearly off the screen.

I can't see anywhere in the code where this might be happening...can you show me the part that creates this list and where the gap might be?

So many thanks!

Rob ( brundlefly1969@gmail.com)

**Comment by VladimirWrites** [comment]
Hi! 🙂
Good catch!👍 I have no idea how I missed that one.

The order of items was wrong. Rate the Watch Face should be the last, as it has space added to the bottom. https://github.com/VladimirWrites/AnalogWatchFace/blob/b13db0993fb3042775bf810eb91bd7dc9ffd7e2f/wear/src/main/res/layout/item_settings_rate.xml#L11

In order to fix it, I simply changed the order.
Here is the commit: https://github.com/VladimirWrites/AnalogWatchFace/commit/b13db0993fb3042775bf810eb91bd7dc9ffd7e2f

I will release the new version right away!

If you are interested in creating your own watch face, I have created a [Pluralsight course that's covering that topic](pluralsight.pxf.io/qBaBY). It's my first course so don't expect amazing quality 😉. Pluralsight is free for the whole month of April if you use this link to register https://pluralsight.pxf.io/ndx17. It doesn't require credit card info to register.

Finally, if you have any questions regarding Wear OS or Android development feel free to write to me at write@vladimirj.dev
