### ISSUE TITLE
Oppo watch heart rate 

### ISSUE THREAD

**Issue by sherifbakhoum** [VladimirWrites/AnalogWatchFace#27]
Good day On oppo watch heart rate complication show only the icon without number please can you fix it  and i would like to ask if it is possible to add numbers tick. Thanks in advance

**Comment by VladimirWrites** [comment]
Sorry to hear that! What happens when you click on that complications?

**Comment by sherifbakhoum** [comment]
It's open the heart rate normal but the complication on the watch face show only the icon without the heart rate number i tried wit other heart rate app downloaded from play store and it showed so i think it's only happening with the stock one. And i would like to ask what about adding tick with number is that possible in next updates? Thanks 😊

**Comment by VladimirWrites** [comment]
It seems that Oppo and Samsung are not exposing the heart rate through complications correctly. I managed to fix the Samsung case, but since I don't have an Oppo watch it would be hard to fix it. But hopefully using the other app fixes the problem for you.
I am working on a new tick layout with numbers right now, but I will probably need a couple more months to finish it.
