### ISSUE TITLE
The HeartRate in complication is not displaying the actual BPM

### ISSUE THREAD

**Issue by MihaiBalica** [VladimirWrites/AnalogWatchFace#36]
This is happening since the last OS update on my galaxy watch 4 and I believe I have the latest watch face version.
Also the battery in one of the other complications is not having the double-circle around it indicating the battery level

![image](https://user-images.githubusercontent.com/37738861/198127459-17fda308-4ef4-4b5f-a45b-458efa123670.png)

**Comment by PLhome** [comment]
On my Ticwatch 3 Pro I am also missing the double circles around the complications since the last update!

**Comment by VladimirWrites** [comment]
Thank you very much for reporting the issue.
The problem with the battery complication will be fixed in the next release, but you will need to remove the complication and set it up again for it to work. It should be out in the next couple of days.

When it comes to Heart rate complications, things are a bit more complicated. Samsung is intentionally hiding heart rate data from 3rd-party watch faces and I got sick of fighting them. Exposing the heart rate complication properly requires a huge amount of hacky code from my side and I just don't have the will and time to support it. If you need a heart rate complication I would recommend buying the [app from amoledwatchfaces™](https://play.google.com/store/apps/details?id=com.weartools.heartratecomp) that exposes heart rate data.

**Comment by PLhome** [comment]
Hi Vladimir,

Thanks for your reply, I can imagine that it is an unfair fight taking up
against these big companies. I am very happy with this very adjustable
watchface and I don't want to switch because of this little issue, keep up
the good work!

Regards,
Peter Lieferink



Op za 5 nov. 2022 17:45 schreef Vladimir Jovanović ***@***.***

**Comment by jweygandt** [comment]
How about simply writing  your own, check out: https://github.com/jweygandt/HonestHeartRateComplication
Way too simple for Play Store, but for developers easy enough

**Comment by PLhome** [comment]
Hi Vladimir,

I did not thank you yet for the latest adjustments, so thank you!
I have a Ticwatch and with the latest update I can see all the indicators
again including battery, heartbeat and saturation.

Regards,
Petet



Op za 5 nov. 2022 20:32 schreef Peter Lieferink ***@***.***>:

**Comment by MihaiBalica** [comment]
Hi, thank you for your feedback and fix, Vladimir. I am using that app you mentioned for the heart BPM and everything is back to normal after latest update. You can close this issue
